import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionAuthProvider } from "@/context/SessionAuthProvider";
import { Header } from "@/components/header";
import { NextUIProviders } from "@/context/nextui-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionAuthProvider>
          <NextUIProviders>
            <Header />
              
            <main className="min-h-screen pt-20">{children}</main>
          </NextUIProviders>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
