import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { SessionAuthProvider } from "@/context/SessionAuthProvider";
import { Header } from "@/components/header";
import { NextUIProviders } from "@/context/nextui-provider";
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`dark ${montserrat.className}`}>
        <SessionAuthProvider>
          <NextUIProviders>
            <Header />

            <main className="main">{children}</main>
          </NextUIProviders>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
